const homeProducts = [
  {
    name: 'PS5 DualSense',
    summary: 'Wireless Controller for Playstation 5',
    description1: `Feel physically responsive feedback to your in-game actions with dual actuators which
          replace traditional rumble motors. In your hands, these dynamic vibrations can
          simulate the feeling of everything from environments to the recoil of different
          weapons.`,
    description2: `Experience varying levels of force and tension as you interact with your in-game gear
          and environments. From pulling back an increasingly tight bowstring to hitting the
          brakes on a speeding car, feel physically connected to your on-screen actions.`,
    compatibility: 'Compatible for Playstation 4 Pro',
    box: [
      { text: 'dsd', quantity: 'dsd' },
      { text: 'd', quantity: 'd' },
      { text: 'd', quantity: 'd' },
      { text: 'd', quantity: 'd' },
    ],
    price_us: '89.99',
    price_eu: '79.99',
    image_dark: 'assets/images/controller.png',
    image_light: 'assets/images/controller2.png',
    availability: 'Available in limited stock',
    id: 'dualsense',
  },
  {
    name: 'ASUS Zephyrus G17',
    description: 'Best Gaming Laptop on the market!',
    compatibility: '144hz, Full DLSS and RTX support',
    price_us: '429.99',
    price_eu: '369.99',
    image_dark: 'assets/images/laptop.png',
    image_light: 'assets/images/laptop2.png',
    availability: '',
    id: 'zephyrus',
  },
  {
    name: 'Logitech G915 TKL',
    description: 'Wireless Optical Mechanical Keyboard',
    compatibility: 'Compatible for Windows/MacOS',
    price_us: '349.99',
    price_eu: '299.99',
    image_dark: 'assets/images/keyboard.png',
    image_light: 'assets/images/keyboard2.png',
    availability: 'Available in limited stock',
    id: 'g915',
  },
  {
    name: 'Xbox Series X Bundle',
    description: 'Gaming Console with Controller',
    compatibility: 'The newest Next-Gen Gaming Consoles',
    price_us: '619.99',
    price_eu: '569.99',
    image_dark: 'assets/images/xbox.png',
    image_light: 'assets/images/xbox2.png',
    availability: '',
    id: 'seriesx',
  },
  {
    name: 'Logitech G-Pro Wireless',
    description: 'Wired & Wireless Gaming Mouse',
    compatibility: 'Best Gaming mouse on the market!',
    price_us: '219.99',
    price_eu: '169.99',
    image_dark: 'assets/images/mouse.png',
    image_light: 'assets/images/mouse2.png',
    availability: 'Available in limited stock',
    id: 'gprowireless',
  },
  {
    name: 'Apple Watch Series 6',
    description: 'Apple Watch 44mm/40mm',
    compatibility: 'Comes in Black/White with a charger included!',
    price_us: '999.99',
    price_eu: '799.99',
    image_dark: 'assets/images/watch.png',
    image_light: 'assets/images/watch2.png',
    availability: 'Available in limited stock',
    id: 'applewatch',
  },
  {
    name: 'Corsair Virtuoso XT',
    description: 'Wireless Gaming Headset',
    compatibility: 'Compatible for all platforms including Switch',
    price_us: '179.99',
    price_eu: '109.99',
    image_dark: 'assets/images/headphones.png',
    image_light: 'assets/images/headphones2.png',
    availability: '',
    id: 'virtuoso',
  },
];
